plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.lab05calculator'
    compileSdk 37

    defaultConfig {
        applicationId 'com.example.lab05calculator'
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
